### ISSUE TITLE
No output when querying the linux.sqlite

### ISSUE THREAD

**Issue by TongweiRen** [Assemblage-Dataset/Assemblage#1] opened 2024-05-15 14:45 UTC
Hi there,

I downloaded the linux.sqlite database and tried to play with it. However, when I ran the following command in the sqlite3 command interface, I didn't get any output.
```
SELECT * FROM functions WHERE binary_id = 1026;
```
I'm not sure why it happened. Could you help me with it?

Thanks.

**Comment by kmicinski** [comment] 2024-05-15 15:06
Thanks for raising this issue. Not sure what’s happening here, we will look
into it, give us a few days to get back to you.

**Comment by changliu98** [comment] 2024-05-16 07:44
Hi Tongwei, the Linux data doesn't come with functions infomation (as we didn't find obvious ways to extract these info in the past), so the functions table is empty. In fact the Linux SQLite databse has only the `binaries` table, while the vcpkg and PE dataset has the detailed function information at this time.

**Comment by kmicinski** [comment] 2024-05-16 12:57
Yes, this is correct to me. We’re looking for fine grained function mapping
for Linux binaries but haven’t found a systematic way yet. Clang allows
dumping ASTs to JSON, we haven’t tried that but it’s possible in principle.
We don’t know how we’d do it for GCC. Maybe DWARF?

**Comment by TongweiRen** [comment] 2024-05-16 14:16
I see, thanks for the clarifying! Just a random asking, do you consider using some reverse engineering tools like Ghidra to process ELF files (with debug information)? 

BTW, please feel free to close the issue, looking forward to seeing more your updates.

**Comment by kmicinski** [comment] 2024-05-16 14:27
Yes, we have some private branches where we run Ghidra or IDA on the binaries. The issue is that it can be "garbage in, garbage out," if you're not careful. Our main focus with the dataset has been to focus on **ground truth** that can be obtained via compilation. However, we will plan on releasing an augmented version of our dataset (with decompilation) at some point in the coming months.

Yes, thanks, please keep in touch, I will close the issue but feel free to email us.

**Closed as completed by kmicinski** 2024-05-16 14:27 UTC
